<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="3" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-08T14:42:47Z" name="Suite" finished-at="2022-08-08T14:45:42Z" duration-ms="175084">
    <groups>
    </groups>
    <test started-at="2022-08-08T14:42:47Z" name="Registration Test Case" finished-at="2022-08-08T14:43:35Z" duration-ms="47295">
      <class name="Academy.registration">
        <test-method is-config="true" signature="intialisation()[pri:0, instance:Academy.registration@55562aa9]" started-at="2022-08-08T20:12:47Z" name="intialisation" finished-at="2022-08-08T20:13:00Z" duration-ms="12358" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialisation -->
        <test-method signature="registration(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Academy.registration@55562aa9]" started-at="2022-08-08T20:13:00Z" name="registration" data-provider="getData" finished-at="2022-08-08T20:13:23Z" duration-ms="23616" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Jitendra]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[jtn3200@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Jay323200#]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Rahul Shetty Academy] but found [RahulShetty]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Rahul Shetty Academy] but found [RahulShetty]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at Academy.registration.registration(registration.java:46)at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)at java.base/java.lang.reflect.Method.invoke(Method.java:577)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registration -->
        <test-method signature="registration(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Academy.registration@55562aa9]" started-at="2022-08-08T20:13:27Z" name="registration" data-provider="getData" finished-at="2022-08-08T20:13:34Z" duration-ms="6928" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Apurva]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[apu@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Jay323200#]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.ElementClickInterceptedException">
            <message>
              <![CDATA[element click intercepted: Element <a href="https://courses.rahulshettyacademy.com/sign_up" class="theme-btn">...</a> is not clickable at point (1054, 27). Other element would receive the click: <div class="preloader" style="opacity: 0.584417;">...</div>  (Session info: chrome=103.0.5060.134)Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'System info: host: 'DESKTOP-BL2TRF2', ip: '192.168.1.6', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.1'Driver info: org.openqa.selenium.chrome.ChromeDriverCapabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 103.0.5060.134, chrome: {chromedriverVersion: 103.0.5060.134 (8ec6fce403b..., userDataDir: C:\Users\Jitendra\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:56330}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}Session ID: 6520cfa7be47788faf04625e9f27e172]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element <a href="https://courses.rahulshettyacademy.com/sign_up" class="theme-btn">...</a> is not clickable at point (1054, 27). Other element would receive the click: <div class="preloader" style="opacity: 0.584417;">...</div>  (Session info: chrome=103.0.5060.134)Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'System info: host: 'DESKTOP-BL2TRF2', ip: '192.168.1.6', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.1'Driver info: org.openqa.selenium.chrome.ChromeDriverCapabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 103.0.5060.134, chrome: {chromedriverVersion: 103.0.5060.134 (8ec6fce403b..., userDataDir: C:\Users\Jitendra\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:56330}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}Session ID: 6520cfa7be47788faf04625e9f27e172at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)at java.base/java.lang.reflect.Method.invoke(Method.java:577)at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)at jdk.proxy2/jdk.proxy2.$Proxy11.click(Unknown Source)at Academy.registration.registration(registration.java:37)at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)at java.base/java.lang.reflect.Method.invoke(Method.java:577)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.ElementClickInterceptedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registration -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:Academy.registration@55562aa9]" started-at="2022-08-08T20:13:34Z" name="afterTest" finished-at="2022-08-08T20:13:35Z" duration-ms="619" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Academy.registration -->
    </test> <!-- Registration Test Case -->
    <test started-at="2022-08-08T14:43:36Z" name="Login Test Case" finished-at="2022-08-08T14:45:13Z" duration-ms="97152">
      <class name="Academy.login">
        <test-method signature="login()[pri:1, instance:Academy.login@5f7b97da]" started-at="2022-08-08T20:13:36Z" name="login" finished-at="2022-08-08T20:14:09Z" duration-ms="33532" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="practice()[pri:2, instance:Academy.login@5f7b97da]" started-at="2022-08-08T20:14:09Z" name="practice" finished-at="2022-08-08T20:14:40Z" duration-ms="30677" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- practice -->
        <test-method signature="autoPractice()[pri:3, instance:Academy.login@5f7b97da]" started-at="2022-08-08T20:14:40Z" name="autoPractice" finished-at="2022-08-08T20:15:13Z" duration-ms="32938" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- autoPractice -->
      </class> <!-- Academy.login -->
    </test> <!-- Login Test Case -->
    <test started-at="2022-08-08T14:45:13Z" name="Data Driven Test Case" finished-at="2022-08-08T14:45:42Z" duration-ms="29297">
      <class name="Academy.dataDrivenregistration">
        <test-method signature="reg()[pri:0, instance:Academy.dataDrivenregistration@315f43d5]" started-at="2022-08-08T20:15:13Z" name="reg" finished-at="2022-08-08T20:15:42Z" duration-ms="29022" status="FAIL">
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[org/apache/commons/io/output/UnsynchronizedByteArrayOutputStream]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: org/apache/commons/io/output/UnsynchronizedByteArrayOutputStreamat dataDriven.dataDriverClass.getData(dataDriverClass.java:28)at Academy.dataDrivenregistration.reg(dataDrivenregistration.java:32)at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)at java.base/java.lang.reflect.Method.invoke(Method.java:577)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.output.UnsynchronizedByteArrayOutputStreamat java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)... 29 more]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reg -->
      </class> <!-- Academy.dataDrivenregistration -->
    </test> <!-- Data Driven Test Case -->
  </suite> <!-- Suite -->
</testng-results>
